# Generated by Django 5.0.4 on 2024-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
