# Generated by Django 5.0.4 on 2024-04-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
