# Generated by Django 5.0.4 on 2024-04-20 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_category_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='items.item'),
            preserve_default=False,
        ),
    ]
