# Generated by Django 5.0.4 on 2024-04-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_photo_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='imageUrl',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
